### ISSUE TITLE
Minimize Console output / add a debug flag for output

### ISSUE THREAD

**Issue by jplacht** [refined-prun/refined-prun#10]
### Description

There is a lot going on in the console with refined-prun being active. I suggest to either get rid of the output or wrap it somehow to require a debug flag being set.

![Screenshot 2024-11-29 at 08 51 16](https://github.com/user-attachments/assets/60e8bbf6-42dd-4eb8-90ec-d8bc193b197a)

**Comment by Razenpok** [comment]
Please include the full log line when you post a log screenshot.

`bundle.xyz.js` files are from prun itself. Ping molp so he could fix it.

<img width="722" alt="image" src="https://github.com/user-attachments/assets/dbdea73b-9f44-4adf-badc-2630e97ee367">
